# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates
version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/.ci'
    schedule:
      interval: 'weekly'
    labels:
      - 'automerge'
    open-pull-requests-limit: 10
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'automerge'
    open-pull-requests-limit: 10
  - package-ecosystem: 'pip'
    directory: '/.ci'
    schedule:
      interval: 'weekly'
    labels:
      - 'automerge'
    open-pull-requests-limit: 10
